APPUSAGE_SQL = """SELECT
    DATETIME (ZOBJECT.ZSTARTDATE + 978307200, 'UNIXEPOCH') AS 'TS_START',
    DATETIME (ZOBJECT.ZENDDATE + 978307200, 'UNIXEPOCH') AS 'TS_END',
    ZOBJECT.ZVALUESTRING AS 'BUNDLE_ID',
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS 'DURATION_SEC',
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) / 60.00 AS 'DURATION_MIN',
    ZSOURCE.ZDEVICEID AS 'DEVICE_ID',
    ZCUSTOMMETADATA.ZNAME AS 'METADATA_NAME',
    ZCUSTOMMETADATA.ZDOUBLEVALUE AS 'METADATA_VALUE',
    CASE ZOBJECT.ZSTARTDAYOFWEEK
        WHEN '1' THEN 'Sunday'
        WHEN '2' THEN 'Monday'
        WHEN '3' THEN 'Tuesday'
        WHEN '4' THEN 'Wednesday'
        WHEN '5' THEN 'Thursday'
        WHEN '6' THEN 'Friday'
        WHEN '7' THEN 'Saturday'
    END AS 'DAY_OF_WEEK',
    ZOBJECT.ZSECONDSFROMGMT / 3600 AS 'GMT_OFFSET',
    DATETIME (ZOBJECT.ZCREATIONDATE + 978307200, 'UNIXEPOCH') AS 'CREATED_AT',
    ZOBJECT.ZUUID AS 'UUID',
    ZSTRUCTUREDMETADATA.ZMETADATAHASH,
    ZOBJECT.Z_PK AS 'ZOBJECT_TABLE_ID'
FROM
    ZOBJECT
    LEFT JOIN ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
    LEFT JOIN ZSOURCE ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK
    LEFT JOIN Z_4EVENT ON ZOBJECT.Z_PK = Z_4EVENT.Z_11EVENT
    LEFT JOIN ZCUSTOMMETADATA ON Z_4EVENT.Z_4CUSTOMMETADATA = ZCUSTOMMETADATA.Z_PK
WHERE
    ZSTREAMNAME = '/app/usage'"""